-- Database schema definition for credit_risk.db SQLite database

-- 1. Main client applications table
CREATE TABLE IF NOT EXISTS application_train (
    SK_ID_CURR INTEGER PRIMARY KEY,
    TARGET INTEGER, -- 1: defaulted, 0: repaid
    NAME_CONTRACT_TYPE TEXT,
    CODE_GENDER TEXT,
    FLAG_OWN_CAR TEXT,
    FLAG_OWN_REALTY TEXT,
    CNT_CHILDREN INTEGER,
    AMT_INCOME_TOTAL REAL,
    AMT_CREDIT REAL,
    AMT_ANNUITY REAL,
    AMT_GOODS_PRICE REAL,
    NAME_INCOME_TYPE TEXT,
    NAME_EDUCATION_TYPE TEXT,
    NAME_FAMILY_STATUS TEXT,
    NAME_HOUSING_TYPE TEXT,
    DAYS_BIRTH INTEGER, -- Age in days (negative)
    DAYS_EMPLOYED INTEGER, -- Employment duration in days (negative)
    OCCUPATION_TYPE TEXT,
    EXT_SOURCE_1 REAL,
    EXT_SOURCE_2 REAL,
    EXT_SOURCE_3 REAL,
    REGION_RATING_CLIENT INTEGER
);

-- 2. Credit Bureau records table
CREATE TABLE IF NOT EXISTS bureau (
    SK_ID_CURR INTEGER,
    SK_ID_BUREAU INTEGER PRIMARY KEY,
    CREDIT_ACTIVE TEXT,
    DAYS_CREDIT INTEGER,
    CREDIT_DAY_OVERDUE INTEGER,
    AMT_CREDIT_SUM REAL,
    AMT_CREDIT_SUM_DEBT REAL,
    AMT_CREDIT_SUM_OVERDUE REAL,
    CREDIT_TYPE TEXT,
    FOREIGN KEY(SK_ID_CURR) REFERENCES application_train(SK_ID_CURR)
);

-- 3. Previous applications at Home Credit table
CREATE TABLE IF NOT EXISTS previous_application (
    SK_ID_CURR INTEGER,
    SK_ID_PREV INTEGER PRIMARY KEY,
    NAME_CONTRACT_TYPE TEXT,
    AMT_APPLICATION REAL,
    AMT_CREDIT REAL,
    AMT_ANNUITY REAL,
    NAME_CONTRACT_STATUS TEXT,
    DAYS_DECISION INTEGER,
    CODE_REJECT_REASON TEXT,
    FOREIGN KEY(SK_ID_CURR) REFERENCES application_train(SK_ID_CURR)
);

-- 4. Joined Client Data table (Pre-aggregated helper view/table)
CREATE TABLE IF NOT EXISTS joined_client_data (
    SK_ID_CURR INTEGER PRIMARY KEY,
    TARGET INTEGER,
    NAME_CONTRACT_TYPE TEXT,
    CODE_GENDER TEXT,
    FLAG_OWN_CAR TEXT,
    FLAG_OWN_REALTY TEXT,
    CNT_CHILDREN INTEGER,
    AMT_INCOME_TOTAL REAL,
    AMT_CREDIT REAL,
    AMT_ANNUITY REAL,
    AMT_GOODS_PRICE REAL,
    NAME_INCOME_TYPE TEXT,
    NAME_EDUCATION_TYPE TEXT,
    NAME_FAMILY_STATUS TEXT,
    NAME_HOUSING_TYPE TEXT,
    DAYS_BIRTH INTEGER,
    DAYS_EMPLOYED INTEGER,
    OCCUPATION_TYPE TEXT,
    EXT_SOURCE_1 REAL,
    EXT_SOURCE_2 REAL,
    EXT_SOURCE_3 REAL,
    REGION_RATING_CLIENT INTEGER,
    -- Engineered aggregates
    BUREAU_LOAN_COUNT INTEGER,
    BUREAU_ACTIVE_LOANS INTEGER,
    BUREAU_MAX_OVERDUE_DAYS INTEGER,
    BUREAU_TOTAL_CREDIT_SUM REAL,
    BUREAU_TOTAL_DEBT REAL,
    BUREAU_TOTAL_OVERDUE REAL,
    PREV_APP_COUNT INTEGER,
    PREV_REFUSED_COUNT INTEGER,
    PREV_AVG_APP_AMT REAL,
    PREV_TOTAL_CREDIT REAL
);
